---
abstract: 'HTML に含まれる絵文字を置換する'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom@gmail.comE<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-ReplacePictogramMobileJp
no_index:
  directory:
    - inc
    - t
provides:
  HTML::ReplacePictogramMobileJp:
    file: lib/HTML/ReplacePictogramMobileJp.pm
    version: 0.07
  HTML::ReplacePictogramMobileJp::AirHPhone:
    file: lib/HTML/ReplacePictogramMobileJp/AirHPhone.pm
    version: 0
  HTML::ReplacePictogramMobileJp::Base:
    file: lib/HTML/ReplacePictogramMobileJp/Base.pm
    version: 0
  HTML::ReplacePictogramMobileJp::DoCoMo:
    file: lib/HTML/ReplacePictogramMobileJp/DoCoMo.pm
    version: 0
  HTML::ReplacePictogramMobileJp::EZweb:
    file: lib/HTML/ReplacePictogramMobileJp/EZweb.pm
    version: 0
  HTML::ReplacePictogramMobileJp::Vodafone:
    file: lib/HTML/ReplacePictogramMobileJp/Vodafone.pm
    version: 0
requires:
  Encode: 0
  Encode::JP::Mobile: 0.22
  File::ShareDir: 0
  Params::Validate: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
