--- 
abstract: "HTML \xE3\x81\xAB\xE5\x90\xAB\xE3\x81\xBE\xE3\x82\x8C\xE3\x82\x8B\xE7\xB5\xB5\xE6\x96\x87\xE5\xAD\x97\xE3\x82\x92\xE7\xBD\xAE\xE6\x8F\x9B\xE3\x81\x99\xE3\x82\x8B"
author: Tokuhiro Matsuno <tokuhirom@gmail.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.650
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTML-ReplacePictogramMobileJp
no_index: 
  directory: 
    - inc
    - t
version: 0.01
